In [2]:
##  Data Doctor
import pandas as pd

data = {
    "Name": ["Alice", "bob", "ALICE", "David", None],
    "Marks": [85, 90, 85, None, 78]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

df["Name"] = df["Name"].fillna("Unknown")
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df = df.drop_duplicates()

df["Name"] = df["Name"].str.lower()

print("\nCleaned Data:")
print(df)

Original Data:
    Name  Marks
0  Alice   85.0
1    bob   90.0
2  ALICE   85.0
3  David    NaN
4   None   78.0

Cleaned Data:
      Name  Marks
0    alice   85.0
1      bob   90.0
2    alice   85.0
3    david   84.5
4  unknown   78.0

In [4]:
import pandas as pd

df = pd.read_csv("students.csv")

print("Original Data:")
display(df.head())

print("\nMissing Values:\n", df.isnull().sum())
print("Duplicate Rows:", df.duplicated().sum())

df = df.ffill()

df = df.drop_duplicates()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower()

print("\nCleaned Data:")
display(df.head())

Original Data:

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6

Missing Values:
 student_id    0
name          0
partner       0
dtype: int64
Duplicate Rows: 0

Cleaned Data:

   student_id            name  partner
0           1   kailash harjo       23
1           2     esha butala        1
2           3  parveen bhalla        3
3           4     marlo dugal       14
4           5     kusum bahri        6